### ISSUE TITLE
Problem with File.Download.bytes on IE10 and IE11

### ISSUE THREAD

**Issue by evancz** [elm/file#10]
The problem was originally reported in https://github.com/elm/file/issues/5, https://github.com/elm/http/issues/56, and https://github.com/elm/http/issues/58.

I got it down to a smaller SSCCE though:

```elm
import Bytes.Encode as E
import File.Download as Download

main =
  Platform.worker
    { init = \() -> ( (), Download.bytes "word.txt" "text/plain" bytes )
    , update = \_ _ -> ( (), Cmd.none )
    , subscriptions = \_ -> Sub.none
    }

bytes =
  E.encode <| E.sequence <|
    List.map E.unsignedInt8 [ 101, 115, 115, 101, 110, 116, 105, 97, 108 ]
```

@boianr mentioned https://github.com/bpampuch/pdfmake/issues/294 which appears to be the same problem. They solved it like this https://github.com/bpampuch/pdfmake/pull/297/files, but my testing suggests that you do not need to go through `Uint8Array` like they did. We just need to get `content.buffer`, but I'm not certain how to account for `content.byteOffset` yet.

**Comment by evancz** [comment]
The tricky case is shown in the following SSCCE, which starts with a `Bytes` value filled with the ASCII for `essential` and trims it down to the ASCII for `sent` before downloading:

```elm
import Bytes.Decode as D
import Bytes.Encode as E
import File.Download as Download

main =
  Platform.worker
    { init = \() -> ( (), download )
    , update = \_ _ -> ( (), Cmd.none )
    , subscriptions = \_ -> Sub.none
    }

bytes =
  E.encode <| E.sequence <|
    List.map E.unsignedInt8 [ 101, 115, 115, 101, 110, 116, 105, 97, 108 ]

download =
  case D.decode decoder bytes of
    Just slice -> Download.bytes "word.txt" "text/plain" slice
    Nothing -> Cmd.none

decoder =
  D.map2 (\_ b -> b) (D.bytes 2) (D.bytes 4)
```

It appears that IE11 is happy when https://github.com/elm/file/blob/master/src/Elm/Kernel/File.js#L49 is changed to the following:

```javascript
var blob = new Blob([new Uint8Array(content.buffer, content,byteOffset, content.byteLength)], {type: mime});
```

This avoids the error folks were seeing, and it ensures that the proper slice of the original `Bytes` value is downloaded. I.e. you only get 4 bytes in the resulting file.

### Question

I could do this in a `try`, but why not just do it by default for all `File.Download.bytes` calls? It should be relatively cheap, and it should work in all the other browsers.

**Comment by evancz** [comment]
The change in https://github.com/elm/file/commit/aecb8d2fbcde4a352626cad0f585ce119ccb32c9 should fix this issue without causing problems in other places, but I want to test it with more browsers. 

I made a file with the change in
[index.html.zip](https://github.com/elm/file/files/2859158/index.html.zip) and it is known to work with the following:

- IE11 on Windows 7
- Safari 12.0.2 on macOS
- Firefox 65 on macOS

Let me know about other browsers!

**Comment by mahulst** [comment]
Works in:
 - Chrome 71.0.3578.98 on macOS
 - Chrome 71.0.3578.98 on Windows 10
 - Edge 44.17763.1.0 on Windows 10
 - IE11 on Windows 10

**Comment by doanythingfordethklok** [comment]
Works in:

Safari Version 12.0.2 (14606.3.4) - MacOS
Firefox Developer edition 65.0b12 (64-bit) - MacOS
Chrome Version 71.0.3578.98 - MacOS
IE 11.0.9600.19236  - Windows 7 (virtualbox images from Microsoft)

**Comment by evancz** [comment]
Exciting! Thank you @mahulst and @doanythingfordethklok for trying it out!

**Comment by jenfan** [comment]
It doesn't work in mobile browsers like safari or chrome

![IMAGE 2019-03-17 23:16:48](https://user-images.githubusercontent.com/5207811/54493412-59640480-4902-11e9-9568-4204fbeab123.jpg)
![IMAGE 2019-03-17 23:16:57](https://user-images.githubusercontent.com/5207811/54493413-5ec14f00-4902-11e9-8785-5ddbffc21eef.jpg)
(tested on iphone 7)

And I cant figure out a way to save pdf file in my app for mobile users. The pdf file saves from server response after uploading form, (then it's generating and send back), so I dont have permanent link to file for easy save.
I will very appreciate for fixing this. Thank you!
