### ISSUE TITLE
Problem with Download.url in IE - Mouse Events

### ISSUE THREAD

**Issue by doanythingfordethklok** [elm/file#11]
This is kinda tangential from #10. 

`Download.url` fails in IE b/c MouseEvent does not have a constructor in IE. Here is the SSCCE (it was cool I learned there was a thing called Platform.worker!)

```
module Main exposing (main)

import File.Download as Download


main =
    Platform.worker
        { init = \() -> ( (), download )
        , update = \_ _ -> ( (), Cmd.none )
        , subscriptions = \_ -> Sub.none
        }


download =
    Download.url "https://media.giphy.com/media/dUQakUPAZw1EY/200w_d.gif"

```

# The Error

<img width="442" alt="screen shot 2019-02-13 at 8 14 45 am" src="https://user-images.githubusercontent.com/1046102/52717962-532fe080-2f70-11e9-8770-a91bb70fbc7d.png">

**Comment by doanythingfordethklok** [comment]
I'm working on a PR. I'll post it today.

**Comment by doanythingfordethklok** [comment]
I have a solution here.  Take a look and LMK what you think and if there is anything you'd like changed.  

https://github.com/elm/file/pull/12

**Comment by evancz** [comment]
It looks like the `download` attribute is not supported by IE in the first place: https://www.w3schools.com/TAGS/att_a_download.asp

So even if clicks work, I would not expect the technique used by `File.Download.url` to work.

* * *

That said, I think this method of clicking will work on IE and minimize the risk of messing up virtual dom stuff.

```javascript
function _File_click(node)
{
	// only needed by IE10 and IE11 to fix https://github.com/elm/file/issues/11
	// all other browsers have MouseEvent and do not need this conditional stuff
	//
	if (typeof MouseEvent === 'function')
	{
		node.dispatchEvent(new MouseEvent('click'));
	}
	else
	{
		var event = document.createEvent('MouseEvents');
		event.initMouseEvent('click', true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
		document.body.appendChild(node);
		node.dispatchEvent(event);
		document.body.removeChild(node);
	}
}
```

It synchronously adds and removes the node from the DOM. This should mean that it does not mess with other things going on. At least, that's my understanding.

* * *

I think doing clicks different can maybe help in other cases, but based on the docs, it shouldn't help in the particular case mentioned here.

**Comment by doanythingfordethklok** [comment]
Why is the `download` attribute relevant to the cmd `File.Download.url`?

**Comment by doanythingfordethklok** [comment]
appending and removing is totally cool.  I put that as a concern in the PR and didn't go nuts spending time on it b/c the whole idea of changing the visible DOM is risky.

**Comment by evancz** [comment]
I have verified that https://github.com/elm/file/commit/c1e742f76106ab42ffe880115fbbc6c6976c4ac0 helps with `File.Select.file` and `File.Select.files`, but I am not sure if there is a clear path for `File.Download.url`.

**Comment by doanythingfordethklok** [comment]
What is it about `File.Download.url` that is concerning and where can I look at the latest PR proposal for resolving it?

**Comment by evancz** [comment]
The latest information on `File.Download.url` is available here:

- [implementation](https://github.com/elm/file/blob/master/src/Elm/Kernel/File.js#L68-L78) - so you can see why the `download` attribute is needed.
- [documentation](https://github.com/elm/file/blob/master/src/File/Download.elm#L31-L65) - 

I saw that other projects will secretly use `XMLHttpRequest` to make things "just work" in the case of cross-origin requests (one synchronous request (!) and one async one) but I felt that it was better to have an implementation that does not have complex conditional behavior that secretly blocks the main thread.

That's what I'm planning to go with given the information I have so far.

**Comment by doanythingfordethklok** [comment]
Agreed. Stay away from the ghost xhr. 

Doing a quick read, `File.Download.url` looks like it'll work in IE. I'll do a test later today and post the result here.

**Comment by doanythingfordethklok** [comment]
`File.Download.url` (the example in the top of this post) works great in IE11 with the code on master. I'm gonna close this issue as it is resolved from my perspective

**Comment by evancz** [comment]
Great, thank you for trying it out and sharing your perspective on what makes sense. It really makes these issues easier to resolve. Should be able to do a patch soon now!
