### ISSUE TITLE
File.Select.files opens a single file browser. 

### ISSUE THREAD

**Issue by rex891** [elm/file#14]
Tried the provided example here: https://ellie-app.com/4KR3vWzcpwFa1

**Comment by BethanyMarriott** [comment]
Also experiencing this. Back tracked versions and File.Select.files works as documented in 1.0.3 but only allows single file selection in 1.0.4.

**Comment by rsignavong** [comment]
I made a PR [#16](https://github.com/elm/file/pull/16)

**Comment by evancz** [comment]
This is due to switching from `setAttribute` to setting the properties directly, but not accounting for the fact that sometimes attributes and properties work differently. @rsignavong figured this out in his PR, which was just merged. Will test everything and do a patch if it looks good.
