### ISSUE TITLE
File.Select requesting csvs in Firefox from "text/plain"

### ISSUE THREAD

**Issue by Torvaney** [elm/file#15]
I have a Cmd Msg of `Select.file ["text/plain"] TextSelected` ([e.g](https://github.com/Torvaney/human-language-model/blob/master/src/Main.elm#L99))., which in Firefox opens a browser window with all files that are not ending `.csv` grayed out and unselectable.

Whereas in Safari, the `.csv` files are grayed out in favour of `.txt` files. In Chrome, both `.csv` and `.txt` files can be selected.

See [Ellie example](https://ellie-app.com/4LLMHKTkMRha1), or ["irl" example](https://torvaney.github.io/projects/human-language-model.html)

**Comment by evancz** [comment]
Can you confirm that this is specific to Elm? What happens when you make an HTML element like:

```html
<input type="file" accept="text/plain"></input>
```

Just try to get it going in an HTML document and share the results!

**Comment by Torvaney** [comment]
Yep, I get the same results as above with the plain html posted above 🤦‍♂️ 

I guess this means it is not an Elm-specific issue.

**Comment by evancz** [comment]
I wonder if there is something about it in the issue tracker for the browsers then. Not sure!

**Comment by Torvaney** [comment]
Yeah, I'll have a look on bugzilla et al. Thanks for your help!
