### ISSUE TITLE
Download.bytes fails in IE10 with InvalidStateError

### ISSUE THREAD

**Issue by boianr** [elm/file#5]
Trying to download `bytes` produces InvalidStateError in IE10.

<img width="1440" alt="screen shot 2019-02-06 at 9 19 45 am" src="https://user-images.githubusercontent.com/32418697/52349043-aeebee00-29f3-11e9-999e-96154b981716.png">

Here is related issue https://github.com/bpampuch/pdfmake/issues/294

Seems that ie10 support for Blob is limited.

**Comment by doanythingfordethklok** [comment]
Alternately, Blob can be polyfilled. Here is one example:
https://github.com/eligrey/Blob.js

**Comment by doanythingfordethklok** [comment]
This ended up fixing the issue..  If the xhr is set to blob, then the `new Blob` code in this library is fine.
 
https://github.com/elm/http/issues/56

There still might be a use case here where an app does some processing to a byte array and wants to send it using Download.bytes and IE would have a problem.  We would need to make a small app isolating this use case.

**Comment by evancz** [comment]
I'm going to use https://github.com/elm/http/issues/58 as the canonical issue for this, even though the fix may ultimately happen in this package. Thank you for the report!
